project:
  type: book

book:
  title: "Value Chain Hackers - Documentation"
  author: "Christiaan Verhoef"
  date: "27/06/2024"
  chapters:
    - index.qmd
    - docs/intro.qmd
    - docs/why.qmd
    - docs/how.qmd
    - docs/what.qmd
    - docs/memorandum.qmd
    - docs/tools.qmd
    - docs/ai/index.qmd
    - docs/student-flow.qmd
    - docs/scrum-process.qmd
    - docs/roles.qmd
    - docs/Webflowui-Guide.qmd
    - docs/resources.qmd
    - docs/summary.qmd
    - docs/presentations/presentations.qmd
    - docs/references.qmd
    - docs/Linkedin-strategy.qmd
    - docs/value-proposition.qmd
    - docs/Company-policy.qmd

bibliography: docs/references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
